### ISSUE TITLE
pod install issue?

### ISSUE THREAD

**Issue by theofficejackpot** [raphaeltraviss/AlphabetSlider#2]
Hi, it could be my ignorance, but maybe it will help someone else. 

I typed 'pod install' , this installed v3.0.0.

I got everything coded (there were swift 4.0 issues, odd I thought), as I was testing, it kept giving me several crashes when moving to different letters.

I then went and manually copy/pasted the (different than pod!) code from your repo: https://github.com/raphaeltraviss/AlphabetSlider/tree/3.x/AlphabetSlider/AlphabetSlider
and it magically worked.

Perhaps the pod is stale?  

Happy user,
DivTracker team

**Comment by raphaeltraviss** [comment]
You're right: pod version should be at 3.0.6, but cocoapods still has 3.0.0; looking into it

**Comment by raphaeltraviss** [comment]
Updated podspec, should be good to go!  version bump to 3.0.7

Thanks for exploring the issue
